version: '3'
services:
  minio_server:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-1234
    command: server --console-address ":9001" /data
    
    networks:
      - common-network

networks:
    common-network:
      external: true
